[package]
name = "checker"
# Keep this version in sync with the one in src/lib.rs!
version = "2.0.0"
edition = "2021"

[lib]
name = "checker"
path = "src/lib.rs"

[dev-dependencies]
rstest = "0.18.2"
