[package]
name = "zk-profiler"
version = "0.1.0"
edition = "2021"

[dependencies]
zk-host = { path = "../pi2" }
risc0-zkvm = { version = "0.19.1", features = ["profiler", "prove"] }
checker = { path = "../../rust" }

[[bin]]
name = "profiler"
path = "src/main.rs"
